# Example Knative/Service manifest for backend deployment.
# Copy to backend-service.yaml and set env vars (use secrets in production).
# CI uses Cloud Run (see .github/workflows/deploy.yml); this file is for reference only.
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: eden-erp-backend
spec:
  template:
    spec:
      containers:
      - image: us-west1-docker.pkg.dev/PROJECT_ID/eden-repo/backend:latest
        ports:
        - name: http1
          containerPort: 8000
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: url
        - name: DATABASE_ECHO
          value: "0"
        - name: APP_ENV
          value: "production"
        - name: CORS_ORIGINS
          value: "*"
